server:
  port: 8082
  


 
spring:
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: http://localhost:9090/
        predicates:
        - Path=/service/**
      - id: AUTH-SERVICE
        uri: http://localhost:9999/
        predicates:
        - Path=/authenticate/**  
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"    application:    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
