server:
  port: 8082
  
  
spring:
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: http://user-container:9090/
        predicates:
        - Path=/service/**
      - id: AUTH-SERVICE
        uri: http://login-container:9999/
        predicates:
        - Path=/authenticate/**  
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"  application:    name: GATEWAY-SERVICE  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://server-container:8761/eureka/
            